spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-group
      topic: wikimedia_recent_change
      auto-offset-reset: earliest

  data:
    mongodb:
      host: localhost
      port: 27017
      database: wikimedia
      uri: mongodb://localhost:27017/wikimedia

  jpa:
    properties:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wikimedia
    username: root
    password: 'Root@1234'